### PR TITLE
No need for a warning when tox-gh does what it's supposed to do

### PR DESCRIPTION
**Pull request by nedbat**
Would you accept this change?  I can work on the test changes if you will, though I'll need some help understanding how to do it.

### CODE REVIEW

**Review by gaborbernat — APPROVED** [review]

**Review by gaborbernat — CHANGES_REQUESTED** [review]
Fix the test, and ensure we assert this message is debug 😊

**Comment by nedbat** [comment]
See if you like what I did with the tests

**Review by gaborbernat — APPROVED** [review]

**Pull request merged**
